### ISSUE TITLE
Call to undefined function pt_load_domdocument() in class-parse-this.php:55

### ISSUE THREAD

**Issue by jackjamieson2** [dshanske/parse-this#43]
Just updated to the latest version and I'm getting this error when running Parse_This->fetch();

```
#4 /home4/karmaco1/public_html/microsub in /home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php on line 55
#3 /home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/includes/class-yarns-microsub-aggregator.php(88): Yarns_Microsub_Aggregator::poll_site('http://boffosoc...', '5c363b3ae35e1', '25')
#2 /home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/includes/class-yarns-microsub-aggregator.php(126): Yarns_Microsub_Parser::parse_feed('http://boffosoc...', 20)
#1 /home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/includes/class-yarns-microsub-parser.php(225): Parse_This->fetch()
#0 /home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php(332): Parse_This->set('<!DOCTYPE html>...', 'http://boffosoc...', false)
Stack trace:
[14-Jun-2019 18:59:01 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function pt_load_domdocument() in /home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php:55
```

**Comment by jackjamieson2** [comment]
Turns out this was a conflict with the version of Parse-This loading in the Post Kinds plugin.
